### PR TITLE
changes

### PR DESCRIPTION
**Pull request by AaravMalani**
- Used `collections.defaultdict` for `invites` instead of `dict`
- Renamed `invites` to `bot.invites` for performance reasons
- Used `python-dotenv` to load credentials
- Removed `createinvite` and used `on_invite_create` instead
- Used only `members` and `invites` intents
- Allowed for multiple invites by one person
- Fixed the vanity bug

### CODE REVIEW

**Comment by xathail** [comment]
Hey! Thanks for making the pull request; I'll be sure to review the changes later.

**Comment by xzerios** [comment]
Also, do you know how I'd go about allowing the bot to work in multiple servers?

**Comment by xzerios** [comment]
Also, do you know how I'd go about allowing the bot to work in multiple servers?

**Comment by xathail** [comment]
The only issue with this request is that it reverts from using bot created invites to user invites. The reason I created this bot in the first place is for the ability to log joins using bot created invites.

Why I made bot invites?
- If a server has a vanity URL, that gets used as the main invite
- E.G if I create an invite, it defaults to the vanity invite of the server, and if I specify an invite to be permanent and support unlimited joins, it'll go to the vanity.

I have included why this bot was created in the readme now to avoid confusion.

**Comment by xathail** [comment]
I'm afraid that this pull request will have to be closed if you aren't able to keep the bot using /createinvite

Edit: I will integrate changes such as token from the .env

**Comment by AaravMalani** [comment]
Ah, but it still would send the vanity url if it was created by the bot, wouldn't it? It's still using the same API call as a user would so I don't see why it wouldn't default to the vanity URL unless there is a check present client-side in the Discord app

**Comment by AaravMalani** [comment]
So it'd be more intuitive to use the inbuilt invite creator where they can change the expiry time and uses to create a custom non-vanity URL

**Comment by xathail** [comment]
Basically, what the code is meant to do is allow the user to create and be allocated an invite from the bot - so the bot creates the invite (this allows the user to be given one of the bot's invites which means they can have a permanent invite that has unlimited uses)

The bot then tracks the joins and if the invite matches one of the created ones, it'll save the joiners UserID to that invite.

It uses the bot's invites to challenge the current way of invite logging as it is quite inefficient, with most invite trackers failing to store joins from temporary invites (which vanities often make you have to use if you want your own invite)

The issue with vanity joins is that the bot saves the UserIDs of people joining from the vanity as the bot invite with the most recent join.

For example, say I have bot invite `x` and someone has bot invite `y`.
Someone joins from invite y and that's fine because it saves the joiner's UserID alongside the y invite.
However, if someone then joins the server with the vanity invite, it'll save the userID to y's invite and make it seem like they joined the server from the bot invite instead.

I hope this cleared things up for you.

**Comment by xathail** [comment]
Fixed errors but altered the way the bot worked. Unfortunately, we couldn't add this.

**Pull request closed without merging**
